return {
  "AstroNvim/astrocore",
  opts = {
    features = {
      large_buf = { size = 1024 * 256, lines = 10000 },
      autopairs = true,
      cmp = true,
      diagnostics = { virtual_text = true, virtual_lines = false },
      highlighturl = true,
      notifications = true,
    },
    diagnostics = {
      virtual_text = true,
      underline = true,
    },
    options = {
      opt = {
        relativenumber = true,
        number = true,
        spell = false,
        signcolumn = "yes",
        wrap = false,
        tabstop = 4,
        shiftwidth = 4,
        expandtab = true,
        smartindent = true,
        swapfile = false,
        backup = false,
        undofile = true,
        hlsearch = false,
        incsearch = true,
        termguicolors = true,
        scrolloff = 8,
        updatetime = 50,
        colorcolumn = "100",
        winfixbuf = false,
      },
      g = {},
    },
    mappings = {
      n = {
        ["<leader>w"] = { "<cmd>w<CR>", desc = "Save file" },
        ["<leader>q"] = { "<cmd>q<CR>", desc = "Quit" },
        ["<leader>qq"] = { "<cmd>qa<CR>", desc = "Quit all" },
        ["<leader>d"] = { vim.diagnostic.open_float, desc = "Open diagnostic float" },
        ["[d"] = { vim.diagnostic.goto_prev, desc = "Prev diagnostic" },
        ["]d"] = { vim.diagnostic.goto_next, desc = "Next diagnostic" },
        ["<leader>pv"] = { "<cmd>Neotree reveal<CR>", desc = "Reveal in file tree" },
        ["<leader>ff"] = { function() require("telescope.builtin").find_files() end, desc = "Find files" },
        ["<leader>fg"] = { function() require("telescope.builtin").live_grep() end, desc = "Live grep" },
        ["<leader>fb"] = { function() require("telescope.builtin").buffers() end, desc = "Find buffers" },
        ["<leader>fh"] = { function() require("telescope.builtin").help_tags() end, desc = "Help tags" },
        ["<leader>e"] = { "<cmd>Neotree toggle<CR>", desc = "Toggle file tree" },
        ["<leader>xx"] = { "<cmd>Trouble diagnostics toggle<CR>", desc = "Diagnostics (Trouble)" },
        ["<leader>xq"] = { "<cmd>Trouble quickfix toggle<CR>", desc = "Quickfix (Trouble)" },
        ["<leader>f"] = {
          function() require("conform").format({ async = true, lsp_fallback = true }) end,
          desc = "Format buffer",
        },
        ["<leader>rn"] = { vim.lsp.buf.rename, desc = "Rename" },
        ["<leader>ca"] = { vim.lsp.buf.code_action, desc = "Code action" },
        ["<leader>rc"] = { "<cmd>RunCode<CR>", desc = "Run code" },
        ["<leader>rf"] = { "<cmd>RunFile<CR>", desc = "Run file" },
        ["<leader>rp"] = { "<cmd>RunProject<CR>", desc = "Run project" },
        ["<leader>rr"] = { "<cmd>RunClose<CR>", desc = "Close run output" },
      },
      v = {
        ["<leader>ca"] = { vim.lsp.buf.code_action, desc = "Code action" },
      },
    },
    treesitter = {
      highlight = true,
      indent = true,
      auto_install = true,
      ensure_installed = {
        "lua",
        "vim",
        "python",
        "rust",
        "bash",
      },
    },
    autocmds = {
      yank_highlight = {
        {
          event = "TextYankPost",
          desc = "Highlight yanked text",
          callback = function() vim.highlight.on_yank({ higroup = "IncSearch", timeout = 200 }) end,
        },
      },
    },
  },
}
